### ISSUE TITLE
【功能需求】三千平台离线安装包提供基地容器镜像 cuda-base 并提供本地构建容器镜像仓库的功能

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#314]
**背景**
类似于保存基底预训练大模型，我们需要为三千平台内置一个容器镜像仓库，然后在离线安装过程中上传基底容器镜像；从而为三千平台上的任务提供快速的容器加载和部署
作为第一步，我们应该将 cuda-base 加载到本地容器镜像仓库里

**这个功能需求是解决什么问题？**
加速容器镜像在三千平台上的部署

**解决方案**
在离线安装包里增加 cuda-base
然后验证一个使用了 cuda-base 作为基底镜像的容器镜像，可以快速拉取
假设该容器镜像的 dockerfile 如下所示：
```Dockerfile
FROM cuda-base
WORKDIR /workspace
copy modihand.py ./modihand.py
```
docker build . -t registry dockerhub.kubekey.local/...

```YAML
...
name: modihand
kind: pytorchjob
image: dockerhub.kubekey.local/...
...
```
此处 modihand pod 应该可以快速拉取
